
export interface County {
  countyNumber: number;
  countyCode: string;
  countyName: string;
}

export const COUNTIES: County[] = [
  { countyNumber: 1, countyCode: 'MSA', countyName: 'Mombasa' },
  { countyNumber: 2, countyCode: 'KWL', countyName: 'Kwale' },
  { countyNumber: 3, countyCode: 'KLF', countyName: 'Kilifi' },
  { countyNumber: 4, countyCode: 'TRV', countyName: 'Tana River' },
  { countyNumber: 5, countyCode: 'LMU', countyName: 'Lamu' },
  { countyNumber: 6, countyCode: 'TVT', countyName: 'Taita/Taveta' },
  { countyNumber: 7, countyCode: 'GRS', countyName: 'Garissa' },
  { countyNumber: 8, countyCode: 'WJR', countyName: 'Wajir' },
  { countyNumber: 9, countyCode: 'MDR', countyName: 'Mandera' },
  { countyNumber: 10, countyCode: 'MST', countyName: 'Marsabit' },
  { countyNumber: 11, countyCode: 'ISO', countyName: 'Isiolo' },
  { countyNumber: 12, countyCode: 'MRU', countyName: 'Meru' },
  { countyNumber: 13, countyCode: 'TKN', countyName: 'Tharaka-Nithi' },
  { countyNumber: 14, countyCode: 'EMB', countyName: 'Embu' },
  { countyNumber: 15, countyCode: 'KTI', countyName: 'Kitui' },
  { countyNumber: 16, countyCode: 'MCK', countyName: 'Machakos' },
  { countyNumber: 17, countyCode: 'MKN', countyName: 'Makueni' },
  { countyNumber: 18, countyCode: 'NRA', countyName: 'Nyandarua' },
  { countyNumber: 19, countyCode: 'NYR', countyName: 'Nyeri' },
  { countyNumber: 20, countyCode: 'KRG', countyName: 'Kirinyaga' },
  { countyNumber: 21, countyCode: 'MRA', countyName: 'Murang&apos;a' },
  { countyNumber: 22, countyCode: 'KBU', countyName: 'Kiambu' },
  { countyNumber: 23, countyCode: 'TKN', countyName: 'Turkana' },
  { countyNumber: 24, countyCode: 'WPT', countyName: 'West Pokot' },
  { countyNumber: 25, countyCode: 'SMR', countyName: 'Samburu' },
  { countyNumber: 26, countyCode: 'TNR', countyName: 'Trans Nzoia' },
  { countyNumber: 27, countyCode: 'UGU', countyName: 'Uasin Gishu' },
  { countyNumber: 28, countyCode: 'ELM', countyName: 'Elgeyo/Marakwet' },
  { countyNumber: 29, countyCode: 'NDI', countyName: 'Nandi' },
  { countyNumber: 30, countyCode: 'BRO', countyName: 'Baringo' },
  { countyNumber: 31, countyCode: 'LKP', countyName: 'Laikipia' },
  { countyNumber: 32, countyCode: 'NRU', countyName: 'Nakuru' },
  { countyNumber: 33, countyCode: 'NRK', countyName: 'Narok' },
  { countyNumber: 34, countyCode: 'KJO', countyName: 'Kajiado' },
  { countyNumber: 35, countyCode: 'KRC', countyName: 'Kericho' },
  { countyNumber: 36, countyCode: 'BOM', countyName: 'Bomet' },
  { countyNumber: 37, countyCode: 'KKG', countyName: 'Kakamega' },
  { countyNumber: 38, countyCode: 'VHG', countyName: 'Vihiga' },
  { countyNumber: 39, countyCode: 'BGA', countyName: 'Bungoma' },
  { countyNumber: 40, countyCode: 'BSA', countyName: 'Busia' },
  { countyNumber: 41, countyCode: 'SYA', countyName: 'Siaya' },
  { countyNumber: 42, countyCode: 'KSM', countyName: 'Kisumu' },
  { countyNumber: 43, countyCode: 'HBY', countyName: 'Homa Bay' },
  { countyNumber: 44, countyCode: 'MGR', countyName: 'Migori' },
  { countyNumber: 45, countyCode: 'KSI', countyName: 'Kisii' },
  { countyNumber: 46, countyCode: 'NYM', countyName: 'Nyamira' },
  { countyNumber: 47, countyCode: 'NBI', countyName: 'Nairobi City' },
];
