
export const COUNTIES = [
  { number: '01', code: 'MSA', name: 'Mombasa' },
  { number: '02', code: 'KWL', name: 'Kwale' },
  { number: '03', code: 'KLF', name: 'Kilifi' },
  { number: '04', code: 'TRV', name: 'Tana River' },
  { number: '05', code: 'LMU', name: 'Lamu' },
  { number: '06', code: 'TVT', name: 'Taita/Taveta' },
  { number: '07', code: 'GRS', name: 'Garissa' },
  { number: '08', code: 'WJR', name: 'Wajir' },
  { number: '09', code: 'MDR', name: 'Mandera' },
  { number: '10', code: 'MST', name: 'Marsabit' },
  { number: '11', code: 'ISO', name: 'Isiolo' },
  { number: '12', code: 'MRU', name: 'Meru' },
  { number: '13', code: 'TKN', name: 'Tharaka-Nithi' },
  { number: '14', code: 'EMB', name: 'Embu' },
  { number: '15', code: 'KTI', name: 'Kitui' },
  { number: '16', code: 'MCK', name: 'Machakos' },
  { number: '17', code: 'MKN', name: 'Makueni' },
  { number: '18', code: 'NRA', name: 'Nyandarua' },
  { number: '19', code: 'NYR', name: 'Nyeri' },
  { number: '20', code: 'KRG', name: 'Kirinyaga' },
  { number: '21', code: 'MRA', name: 'Murang&apos;a' },
  { number: '22', code: 'KBU', name: 'Kiambu' },
  { number: '23', code: 'TKN', name: 'Turkana' },
  { number: '24', code: 'WPT', name: 'West Pokot' },
  { number: '25', code: 'SMR', name: 'Samburu' },
  { number: '26', code: 'TNR', name: 'Trans Nzoia' },
  { number: '27', code: 'UGU', name: 'Uasin Gishu' },
  { number: '28', code: 'ELM', name: 'Elgeyo/Marakwet' },
  { number: '29', code: 'NDI', name: 'Nandi' },
  { number: '30', code: 'BRO', name: 'Baringo' },
  { number: '31', code: 'LKP', name: 'Laikipia' },
  { number: '32', code: 'NRU', name: 'Nakuru' },
  { number: '33', code: 'NRK', name: 'Narok' },
  { number: '34', code: 'KJO', name: 'Kajiado' },
  { number: '35', code: 'KRC', name: 'Kericho' },
  { number: '36', code: 'BOM', name: 'Bomet' },
  { number: '37', code: 'KKG', name: 'Kakamega' },
  { number: '38', code: 'VHG', name: 'Vihiga' },
  { number: '39', code: 'BGA', name: 'Bungoma' },
  { number: '40', code: 'BSA', name: 'Busia' },
  { number: '41', code: 'SYA', name: 'Siaya' },
  { number: '42', code: 'KSM', name: 'Kisumu' },
  { number: '43', code: 'HBY', name: 'Homa Bay' },
  { number: '44', code: 'MGR', name: 'Migori' },
  { number: '45', code: 'KSI', name: 'Kisii' },
  { number: '46', code: 'NYM', name: 'Nyamira' },
  { number: '47', code: 'NBI', name: 'Nairobi City' },
];

export const SERVICE_CATEGORIES = [
  'Plumbing',
  'Electrical',
  'Carpentry',
  'Painting',
  'Cleaning',
  'Gardening',
  'Masonry',
  'Welding',
  'Roofing',
  'Tiling',
  'Security',
  'Catering',
  'Driving',
  'Delivery',
  'Moving',
  'Laundry',
  'Tailoring',
  'Hair & Beauty',
  'Childcare',
  'Elderly Care',
  'Pet Care',
  'Tutoring',
  'IT Support',
  'Photography',
  'Event Planning',
];

export const TRAINING_OPTIONS = [
  'Certified Plumber',
  'Licensed Electrician',
  'Carpentry Certificate',
  'Professional Painter',
  'Cleaning Professional',
  'Landscaping Certificate',
  'Masonry Training',
  'Welding Certificate',
  'Roofing Specialist',
  'Tiling Expert',
  'Security Training',
  'Culinary Arts',
  'Professional Driver License',
  'First Aid Certified',
  'Childcare Certificate',
  'Elderly Care Training',
  'Pet Care Professional',
  'Teaching Certificate',
  'IT Certification',
  'Photography Course',
  'Event Management',
];
